import type {
  Bike,
  EventCheckIn,
  InstalledPart,
  PartRequest,
  RequestResponse,
  SparePart,
  TrackEvent,
  User,
} from "@/lib/types";

export const currentUser: User = {
  id: "u-cody",
  name: "Cody Johnson",
  email: "cody@example.com",
  homeTrack: "Circuit of the Americas",
};

export const demoUsers: User[] = [
  currentUser,
  { id: "u-mia", name: "Mia Torres", email: "mia@example.com", homeTrack: "MSR Houston" },
  { id: "u-jay", name: "Jay Patel", email: "jay@example.com", homeTrack: "Eagles Canyon" },
];

export const demoBikes: Bike[] = [
  {
    id: "bike-r6",
    userId: currentUser.id,
    year: 2020,
    make: "Yamaha",
    model: "R6",
    nickname: "Blue spare bike",
    useType: "track",
    notes: "Race bodywork, stock engine, common R6 crash spares fit.",
    photos: [],
  },
];

export const demoInstalledParts: InstalledPart[] = [
  {
    id: "ip-1",
    bikeId: "bike-r6",
    name: "Attack triple clamps",
    category: "triple clamp",
    brand: "Attack",
    side: "universal",
    compatibilityTags: ["yamaha-r6", "2017-2020-r6", "attack"],
    notes: "Source only if damaged.",
    photos: [],
    safetyCategory: "source_only",
  },
  {
    id: "ip-2",
    bikeId: "bike-r6",
    name: "Woodcraft clip ons",
    category: "clip on",
    brand: "Woodcraft",
    side: "universal",
    compatibilityTags: ["50mm", "clip-on-tube", "woodcraft", "yamaha-r6"],
    notes: "Uses 50mm clamps and replaceable tubes.",
    photos: [],
    safetyCategory: "red",
  },
  {
    id: "ip-3",
    bikeId: "bike-r6",
    name: "Vortex rearsets",
    category: "rearset",
    brand: "Vortex",
    side: "universal",
    compatibilityTags: ["vortex", "r6-rearset", "toe-peg", "shift-rod"],
    notes: "Carry spare pegs and rods.",
    photos: [],
    safetyCategory: "red",
  },
];

export const demoEvent: TrackEvent = {
  id: "event-cota-may",
  trackName: "Circuit of the Americas",
  organizer: "RideSmart",
  startDate: "2026-05-24",
  endDate: "2026-05-24",
  location: "Austin, TX",
  notes: "Hot pit open at 7:00. Vendors near garages 2-4.",
};

export const demoCheckIns: EventCheckIn[] = [
  {
    id: "ci-1",
    eventId: demoEvent.id,
    userId: currentUser.id,
    riderName: currentUser.name,
    paddockLocation: "Blue canopy, row C",
    visibleInventoryEnabled: true,
    checkedInAt: "2026-05-24T07:12:00Z",
  },
  {
    id: "ci-2",
    eventId: demoEvent.id,
    userId: "u-mia",
    riderName: "Mia Torres",
    paddockLocation: "Garage 3",
    visibleInventoryEnabled: true,
    checkedInAt: "2026-05-24T07:30:00Z",
  },
  {
    id: "ci-3",
    eventId: demoEvent.id,
    userId: "u-jay",
    riderName: "Jay Patel",
    paddockLocation: "Black trailer by tech",
    visibleInventoryEnabled: true,
    checkedInAt: "2026-05-24T08:02:00Z",
  },
];

export const demoSpares: SparePart[] = [
  {
    id: "sp-clip-50",
    userId: "u-mia",
    ownerName: "Mia Torres",
    name: "50mm clip on tube",
    category: "clip on",
    brand: "Woodcraft",
    partNumber: "12-0450",
    quantity: 2,
    condition: "Used, straight",
    side: "universal",
    compatibilityTags: ["50mm", "clip-on-tube", "woodcraft", "vortex", "attack", "yamaha-r6"],
    availabilityStatus: "sell",
    price: 25,
    notes: "Bring your clamp. Tube only.",
    photos: [],
    safetyCategory: "red",
    visibility: "public_at_event",
    visibleAtEvents: [demoEvent.id],
    fitmentAttributes: { forkDiameterMm: 50 },
  },
  {
    id: "sp-lever",
    userId: "u-jay",
    ownerName: "Jay Patel",
    name: "Brembo RCS brake lever blade",
    category: "brake lever",
    brand: "Brembo",
    quantity: 1,
    condition: "New",
    side: "right",
    compatibilityTags: ["brembo", "rcs", "brake", "lever-blade"],
    availabilityStatus: "emergency_only",
    depositRequired: "Replace by next event",
    notes: "Fits my RCS 19. Verify pivot and adjuster.",
    photos: [],
    safetyCategory: "source_only",
    visibility: "public_at_event",
    visibleAtEvents: [demoEvent.id],
  },
  {
    id: "sp-peg",
    userId: currentUser.id,
    ownerName: currentUser.name,
    name: "Vortex toe peg",
    category: "toe peg",
    brand: "Vortex",
    quantity: 4,
    condition: "New",
    side: "universal",
    compatibilityTags: ["vortex", "toe-peg", "rearset", "yamaha-r6"],
    availabilityStatus: "lend",
    notes: "Small hardware bag in top drawer.",
    photos: [],
    safetyCategory: "yellow",
    visibility: "public_at_event",
    visibleAtEvents: [demoEvent.id],
  },
  {
    id: "sp-bracket",
    userId: "u-mia",
    ownerName: "Mia Torres",
    name: "Brake reservoir bracket",
    category: "reservoir bracket",
    brand: "Generic",
    quantity: 3,
    condition: "Mixed",
    side: "right",
    compatibilityTags: ["reservoir", "bracket", "universal", "zip-tie-backup"],
    availabilityStatus: "lend",
    notes: "Aluminum strip brackets. Verify clearance.",
    photos: [],
    safetyCategory: "yellow",
    visibility: "public_at_event",
    visibleAtEvents: [demoEvent.id],
  },
  {
    id: "sp-masterlink",
    userId: "u-jay",
    ownerName: "Jay Patel",
    name: "520 master link",
    category: "master link",
    brand: "DID",
    quantity: 5,
    condition: "New",
    side: "universal",
    compatibilityTags: ["520", "chain", "did", "master-link"],
    availabilityStatus: "sell",
    price: 8,
    notes: "Clip and rivet style in kit.",
    photos: [],
    safetyCategory: "red",
    visibility: "public_at_event",
    visibleAtEvents: [demoEvent.id],
  },
];

export const demoRequests: PartRequest[] = [
  {
    id: "req-1",
    eventId: demoEvent.id,
    userId: currentUser.id,
    bikeId: "bike-r6",
    title: "Need right-side 50mm clip on tube",
    partNeeded: "50mm clip on tube",
    category: "clip on",
    urgency: "session_critical",
    side: "right",
    description: "Crashed in session 2. Tube is bent. Will buy or replace.",
    photos: [],
    compatibilityTags: ["50mm", "clip-on-tube", "woodcraft", "yamaha-r6"],
    status: "open",
    requestType: "buy",
    createdAt: "2026-05-24T10:12:00Z",
  },
];

export const demoResponses: RequestResponse[] = [
  {
    id: "rr-1",
    requestId: "req-1",
    responderUserId: "u-mia",
    responderName: "Mia Torres",
    message: "I have two 50mm Woodcraft tubes in Garage 3. Bring the clamp to verify.",
    offeredSparePartId: "sp-clip-50",
    responseType: "have_this",
    createdAt: "2026-05-24T10:14:00Z",
  },
];

export const crashZones = [
  "left side",
  "right side",
  "front",
  "rear",
  "controls",
  "bodywork",
  "cooling",
  "electronics",
  "drivetrain",
  "unknown",
];

export const inspectionChecklists: Record<string, string[]> = {
  "right side": [
    "brake lever",
    "throttle tube",
    "bar end",
    "clip on",
    "master cylinder",
    "front brake line",
    "right rearset",
    "brake pedal",
    "foot peg",
    "exhaust hanger",
    "frame slider",
    "case cover",
    "fairing bracket",
    "radiator clearance",
  ],
  "left side": [
    "clutch lever",
    "clip on",
    "bar end",
    "left rearset",
    "shift rod",
    "toe peg",
    "frame slider",
    "case cover",
    "fairing bracket",
    "stator cover",
  ],
  front: ["front wheel", "brake rotors", "forks", "clip ons", "brake lines", "front axle", "fairing stay"],
  rear: ["rear wheel", "rear axle", "chain", "sprocket", "rear brake", "subframe", "exhaust hanger"],
  controls: ["brake lever", "clutch lever", "throttle tube", "clip on", "switch pod", "master cylinder"],
  bodywork: ["dzus fasteners", "fairing bracket", "windscreen", "tail section", "belly pan"],
  cooling: ["radiator", "radiator cap", "hose clamp", "coolant overflow", "fan clearance"],
  electronics: ["kill switch", "quick shifter", "battery cable", "dash mount", "sensor connector"],
  drivetrain: ["chain", "master link", "shift rod", "sprocket", "clutch lever", "rearset"],
  unknown: ["controls", "brakes", "wheels", "suspension", "cooling", "fluid leaks", "bodywork clearance"],
};
