import type {
  Bike,
  EventCheckIn,
  InstalledPart,
  PartRequest,
  RequestResponse,
  SparePart,
  TrackEvent,
  User,
} from "@/lib/types";

// Frozen "now" so SSR and client hydration see identical relative-time output.
// Bump this when you want the demo to feel fresh.
export const DEMO_NOW = new Date("2026-05-17T14:30:00Z").getTime();
const ago = (ms: number) => new Date(DEMO_NOW - ms).toISOString();

export const currentUser: User = {
  id: "u-cody",
  name: "Cody Johnson",
  email: "cody@example.com",
  homeTrack: "Buttonwillow Raceway",
};

export const demoUsers: User[] = [
  currentUser,
  { id: "u-mia", name: "Mia Torres", email: "mia@example.com", homeTrack: "Buttonwillow" },
  { id: "u-jay", name: "Jay Patel", email: "jay@example.com", homeTrack: "Buttonwillow" },
  { id: "u-marco", name: "Marco V.", email: "marco@example.com" },
  { id: "u-jess", name: "Jess T.", email: "jess@example.com" },
  { id: "u-owen", name: "Owen K.", email: "owen@example.com" },
  { id: "u-sami", name: "Sami R.", email: "sami@example.com" },
  { id: "u-devon", name: "Devon S.", email: "devon@example.com" },
  { id: "u-heru", name: "Heru Fab", email: "heru@example.com" },
  { id: "u-ana", name: "Ana P.", email: "ana@example.com" },
];

export const demoBikes: Bike[] = [
  {
    id: "bike-r6",
    userId: currentUser.id,
    year: 2020,
    make: "Yamaha",
    model: "R6",
    nickname: "Goblin",
    useType: "track",
    notes:
      "Race-prepped only. Spare bar set is in the trailer. Steering damper at 4 clicks for Buttonwillow. Fork oil last changed Feb '26.",
    photos: [],
  },
  {
    id: "bike-r6-backup",
    userId: currentUser.id,
    year: 2017,
    make: "Yamaha",
    model: "R6",
    nickname: "Sparky",
    useType: "track",
    notes: "Backup. Lives in the trailer. Shares most consumables with the Goblin.",
    photos: [],
  },
  {
    id: "bike-rs",
    userId: currentUser.id,
    year: 2022,
    make: "Aprilia",
    model: "RS660",
    nickname: "Daily",
    useType: "street",
    notes: "Street commuter. Not on the trailer at events.",
    photos: [],
  },
];

export const demoInstalledParts: InstalledPart[] = [
  {
    id: "ip-1",
    bikeId: "bike-r6",
    name: "Attack Performance triple clamps",
    category: "triple clamp",
    brand: "Attack",
    partNumber: "AT-R6-TRP",
    side: "universal",
    compatibilityTags: ["yamaha-r6", "50mm", "attack"],
    notes: "50mm clip-on bore.",
    photos: [],
    safetyCategory: "red",
  },
  {
    id: "ip-2",
    bikeId: "bike-r6",
    name: "Woodcraft 3-piece clip ons",
    category: "clip on",
    brand: "Woodcraft",
    partNumber: "WC-3PC-50",
    side: "universal",
    compatibilityTags: ["50mm", "M10x1.25", "woodcraft"],
    notes: "Uses 50mm clamps and replaceable tubes.",
    photos: [],
    safetyCategory: "red",
  },
  {
    id: "ip-3",
    bikeId: "bike-r6",
    name: "Brembo RCS 19×18 master cylinder",
    category: "master cylinder",
    brand: "Brembo",
    partNumber: "110.A263.30",
    side: "right",
    compatibilityTags: ["brembo", "rcs", "19x18", "radial"],
    notes: "Verify torque before riding.",
    photos: [],
    safetyCategory: "source_only",
  },
  {
    id: "ip-4",
    bikeId: "bike-r6",
    name: "Vortex V3 rearsets",
    category: "rearset",
    brand: "Vortex",
    side: "universal",
    compatibilityTags: ["vortex", "v3", "reverse-shift"],
    notes: "Reverse shift pattern.",
    photos: [],
    safetyCategory: "red",
  },
  {
    id: "ip-5",
    bikeId: "bike-r6",
    name: "Armour Bodies race bodywork",
    category: "bodywork",
    brand: "Armour",
    side: "universal",
    compatibilityTags: ["6-piece", "dzus", "pre-cut"],
    notes: "6 piece, pre-cut dzus.",
    photos: [],
    safetyCategory: "yellow",
  },
  {
    id: "ip-6",
    bikeId: "bike-r6",
    name: "GB Racing case covers",
    category: "case cover",
    brand: "GB Racing",
    side: "universal",
    compatibilityTags: ["alternator", "clutch", "pulse"],
    notes: "Alternator + clutch + pulse.",
    photos: [],
    safetyCategory: "green",
  },
];

export const demoEvent: TrackEvent = {
  id: "event-bw-may",
  trackName: "Buttonwillow Raceway",
  organizer: "Trackdaz",
  startDate: "2026-05-17",
  endDate: "2026-05-18",
  location: "Buttonwillow, CA",
  notes:
    "Pit-out closes at 5:10pm. Riders' group meeting at the white tent after lunch — bring tear-offs. Track temp 38°C, dropping.",
};

export const demoCheckIns: EventCheckIn[] = [
  {
    id: "ci-cody",
    eventId: demoEvent.id,
    userId: currentUser.id,
    riderName: currentUser.name,
    paddockLocation: "P15",
    visibleInventoryEnabled: true,
    checkedInAt: "2026-05-17T09:14:00Z",
  },
  { id: "ci-mia", eventId: demoEvent.id, userId: "u-mia", riderName: "Mia Torres", paddockLocation: "P8", visibleInventoryEnabled: true, checkedInAt: "2026-05-17T07:30:00Z" },
  { id: "ci-jay", eventId: demoEvent.id, userId: "u-jay", riderName: "Jay Patel", paddockLocation: "P12", visibleInventoryEnabled: true, checkedInAt: "2026-05-17T08:02:00Z" },
  { id: "ci-marco", eventId: demoEvent.id, userId: "u-marco", riderName: "Marco V.", paddockLocation: "P3", visibleInventoryEnabled: true, checkedInAt: "2026-05-17T07:10:00Z" },
  { id: "ci-jess", eventId: demoEvent.id, userId: "u-jess", riderName: "Jess T.", paddockLocation: "P11", visibleInventoryEnabled: true, checkedInAt: "2026-05-17T07:42:00Z" },
  { id: "ci-owen", eventId: demoEvent.id, userId: "u-owen", riderName: "Owen K.", paddockLocation: "P22", visibleInventoryEnabled: true, checkedInAt: "2026-05-17T08:30:00Z" },
  { id: "ci-sami", eventId: demoEvent.id, userId: "u-sami", riderName: "Sami R.", paddockLocation: "P7", visibleInventoryEnabled: true, checkedInAt: "2026-05-17T08:15:00Z" },
  { id: "ci-devon", eventId: demoEvent.id, userId: "u-devon", riderName: "Devon S.", paddockLocation: "P9", visibleInventoryEnabled: true, checkedInAt: "2026-05-17T08:01:00Z" },
  { id: "ci-heru", eventId: demoEvent.id, userId: "u-heru", riderName: "Heru Fab", paddockLocation: "vendor trailer", visibleInventoryEnabled: true, checkedInAt: "2026-05-17T06:45:00Z" },
  { id: "ci-ana", eventId: demoEvent.id, userId: "u-ana", riderName: "Ana P.", paddockLocation: "P14", visibleInventoryEnabled: true, checkedInAt: "2026-05-17T07:55:00Z" },
];

export const demoSpares: SparePart[] = [
  {
    id: "sp-clip-50-l",
    userId: currentUser.id,
    ownerName: currentUser.name,
    name: "Woodcraft clip-on tube",
    category: "clip on",
    brand: "Woodcraft",
    partNumber: "WC-3PC-50L",
    quantity: 1,
    condition: "used · straight",
    side: "left",
    compatibilityTags: ["50mm", "M10x1.25", "Woodcraft", "Vortex", "Attack"],
    availabilityStatus: "emergency_only",
    notes: "Used straight LEFT tube. Bring clamp & bar end.",
    photos: [],
    safetyCategory: "red",
    visibility: "public_at_event",
    visibleAtEvents: [demoEvent.id],
    fitmentAttributes: { forkDiameterMm: 50, pinchBolt: "M10x1.25" },
  },
  {
    id: "sp-brembo-lever",
    userId: currentUser.id,
    ownerName: currentUser.name,
    name: "Brembo RCS lever",
    category: "brake lever",
    brand: "Brembo",
    partNumber: "110.A263.10",
    quantity: 1,
    condition: "new in box",
    side: "right",
    compatibilityTags: ["Brembo", "RCS", "forged"],
    availabilityStatus: "sell",
    price: 120,
    notes: "Forged blade. Fits RCS 19.",
    photos: [],
    safetyCategory: "source_only",
    visibility: "public_at_event",
    visibleAtEvents: [demoEvent.id],
  },
  {
    id: "sp-vortex-peg",
    userId: currentUser.id,
    ownerName: currentUser.name,
    name: "Vortex V3 toe peg",
    category: "rearset peg",
    brand: "Vortex",
    partNumber: "V3-TP-22",
    quantity: 2,
    condition: "lightly scuffed",
    side: "universal",
    compatibilityTags: ["Vortex", "22mm", "knurled"],
    availabilityStatus: "trade",
    notes: "Open to trade for matching shift rod.",
    photos: [],
    safetyCategory: "yellow",
    visibility: "public_at_event",
    visibleAtEvents: [demoEvent.id],
  },
  {
    id: "sp-dzus",
    userId: currentUser.id,
    ownerName: currentUser.name,
    name: "Dzus fasteners 7mm",
    category: "dzus fastener",
    brand: "Generic",
    partNumber: "DZ-7-SLT",
    quantity: 12,
    condition: "new",
    side: "universal",
    compatibilityTags: ["7mm", "slotted", "dzus"],
    availabilityStatus: "lend",
    notes: "Pull anything you need from the kit.",
    photos: [],
    safetyCategory: "green",
    visibility: "public_at_event",
    visibleAtEvents: [demoEvent.id],
  },
  {
    id: "sp-slider-puck",
    userId: currentUser.id,
    ownerName: currentUser.name,
    name: "Frame slider puck",
    category: "slider puck",
    brand: "Woodcraft",
    partNumber: "WC-SLD-PK",
    quantity: 1,
    condition: "lightly used",
    side: "right",
    compatibilityTags: ["Woodcraft", "M10"],
    availabilityStatus: "sell",
    price: 30,
    notes: "Replacement puck only.",
    photos: [],
    safetyCategory: "green",
    visibility: "private",
    visibleAtEvents: [],
  },
  // Some spares from OTHER paddock members so matching has results
  {
    id: "sp-clip-50-r-devon",
    userId: "u-devon",
    ownerName: "Devon S.",
    name: "Vortex V3 50mm clip-on tube",
    category: "clip on",
    brand: "Vortex",
    partNumber: "V3-CLP-50R",
    quantity: 1,
    condition: "off 2018 R6",
    side: "right",
    compatibilityTags: ["50mm", "M10x1.25", "Vortex", "Woodcraft", "Attack", "yamaha-r6"],
    availabilityStatus: "lend",
    notes: "Lend for the weekend.",
    photos: [],
    safetyCategory: "red",
    visibility: "public_at_event",
    visibleAtEvents: [demoEvent.id],
    fitmentAttributes: { forkDiameterMm: 50, pinchBolt: "M10x1.25" },
  },
  {
    id: "sp-clip-50-r-heru",
    userId: "u-heru",
    ownerName: "Heru Fab",
    name: "Woodcraft 3-piece 50mm RIGHT",
    category: "clip on",
    brand: "Woodcraft",
    partNumber: "WC-3PC-50R",
    quantity: 4,
    condition: "new in box",
    side: "right",
    compatibilityTags: ["50mm", "M10x1.25", "Woodcraft", "in-stock"],
    availabilityStatus: "sell",
    price: 145,
    notes: "Stocked at vendor onsite.",
    photos: [],
    safetyCategory: "red",
    visibility: "public_at_event",
    visibleAtEvents: [demoEvent.id],
  },
  {
    id: "sp-clip-50-sami",
    userId: "u-sami",
    ownerName: "Sami R.",
    name: "Universal 50mm tube",
    category: "clip on",
    brand: "Generic",
    quantity: 1,
    condition: "unknown",
    side: "universal",
    compatibilityTags: ["50mm"],
    availabilityStatus: "lend",
    notes: "Free if it works for you.",
    photos: [],
    safetyCategory: "red",
    visibility: "public_at_event",
    visibleAtEvents: [demoEvent.id],
  },
];

export const demoRequests: PartRequest[] = [
  {
    id: "req-marco-clip",
    eventId: demoEvent.id,
    userId: "u-marco",
    bikeId: "bike-r6",
    title: "50mm clip-on tube, RIGHT",
    partNeeded: "50mm clip on tube",
    category: "clip on",
    urgency: "session_critical",
    side: "right",
    description:
      "Lowsided into T6. Right clip-on tube bent, bar end gouged. Bike is otherwise straight — wheel and forks check OK by eye but I need to ride afternoon sessions. Will buy outright or swap for a spare set.",
    photos: [],
    compatibilityTags: ["Woodcraft", "Vortex", "Attack", "50mm", "M10x1.25"],
    status: "open",
    requestType: "buy",
    createdAt: ago(4 * 60 * 1000),
  },
  {
    id: "req-jess-lever",
    eventId: demoEvent.id,
    userId: "u-jess",
    bikeId: "bike-r6",
    title: "Brake lever — adjustable",
    partNeeded: "brake lever",
    category: "brake lever",
    urgency: "today",
    side: "right",
    description: "Need adjustable forged lever before afternoon session.",
    photos: [],
    compatibilityTags: ["Brembo RCS", "M19", "forged"],
    status: "pending",
    requestType: "borrow",
    createdAt: ago(22 * 60 * 1000),
  },
  {
    id: "req-owen-rad",
    eventId: demoEvent.id,
    userId: "u-owen",
    bikeId: "bike-r6",
    title: "Radiator hose, lower (heat damage)",
    partNeeded: "radiator hose",
    category: "cooling",
    urgency: "today",
    side: "universal",
    description: "Lower hose split. Silicone OK as paddock fix.",
    photos: [],
    compatibilityTags: ["silicone OK", "32mm ID"],
    status: "open",
    requestType: "buy",
    createdAt: ago(38 * 60 * 1000),
  },
  {
    id: "req-sami-dzus",
    eventId: demoEvent.id,
    userId: "u-sami",
    bikeId: "bike-r6",
    title: "Fairing dzus — 7mm slotted ×6",
    partNeeded: "dzus fastener",
    category: "dzus fastener",
    urgency: "low",
    side: "universal",
    description: "Trade or buy 6 dzus fasteners.",
    photos: [],
    compatibilityTags: ["7mm", "slotted"],
    status: "open",
    requestType: "trade",
    createdAt: ago(60 * 60 * 1000),
  },
  {
    id: "req-ana-warm",
    eventId: demoEvent.id,
    userId: "u-ana",
    bikeId: "bike-r6",
    title: "Tire warmers, 17in front + rear",
    partNeeded: "tire warmers",
    category: "hardware",
    urgency: "low",
    side: "universal",
    description: "Borrow for afternoon.",
    photos: [],
    compatibilityTags: ["120/70", "190/55"],
    status: "resolved",
    requestType: "borrow",
    createdAt: ago(2 * 60 * 60 * 1000),
  },
];

export const demoResponses: RequestResponse[] = [
  {
    id: "rr-heru-marco",
    requestId: "req-marco-clip",
    responderUserId: "u-heru",
    responderName: "Heru Fab",
    message: "50mm Woodcraft tube in stock at trailer — $145. Bring bar end.",
    offeredSparePartId: "sp-clip-50-r-heru",
    responseType: "vendor_has_one",
    createdAt: ago(3 * 60 * 1000),
  },
  {
    id: "rr-devon-marco",
    requestId: "req-marco-clip",
    responderUserId: "u-devon",
    responderName: "Devon S.",
    message: "I have a Vortex 50mm RIGHT off my old R6, never crashed. Lend OK.",
    offeredSparePartId: "sp-clip-50-r-devon",
    responseType: "may_fit",
    createdAt: ago(2 * 60 * 1000),
  },
  {
    id: "rr-eli-marco",
    requestId: "req-marco-clip",
    responderUserId: "u-jay",
    responderName: "Jay Patel",
    message: "If the bar moves at all under hand pressure, don't ride. Replace, don't straighten.",
    responseType: "do_not_ride",
    createdAt: ago(60 * 1000),
  },
  {
    id: "rr-jess-1",
    requestId: "req-jess-lever",
    responderUserId: currentUser.id,
    responderName: currentUser.name,
    message: "I have a forged RCS lever new in box at P15. $120 or borrow with deposit.",
    offeredSparePartId: "sp-brembo-lever",
    responseType: "have_this",
    createdAt: ago(18 * 60 * 1000),
  },
];

export const crashZones = [
  "left side",
  "right side",
  "front",
  "rear",
  "controls",
  "bodywork",
  "cooling",
  "electronics",
  "drivetrain",
  "unknown",
];

export const inspectionChecklists: Record<string, string[]> = {
  "right side": [
    "brake lever",
    "throttle tube",
    "bar end",
    "clip on",
    "master cylinder",
    "front brake line",
    "right rearset",
    "brake pedal",
    "foot peg",
    "exhaust hanger",
    "frame slider",
    "case cover",
    "fairing bracket",
    "radiator clearance",
  ],
  "left side": [
    "clutch lever",
    "clip on",
    "bar end",
    "left rearset",
    "shift rod",
    "toe peg",
    "frame slider",
    "case cover",
    "fairing bracket",
    "stator cover",
  ],
  front: ["front wheel", "brake rotors", "forks", "clip ons", "brake lines", "front axle", "fairing stay"],
  rear: ["rear wheel", "rear axle", "chain", "sprocket", "rear brake", "subframe", "exhaust hanger"],
  controls: ["brake lever", "clutch lever", "throttle tube", "clip on", "switch pod", "master cylinder"],
  bodywork: ["dzus fasteners", "fairing bracket", "windscreen", "tail section", "belly pan"],
  cooling: ["radiator", "radiator cap", "hose clamp", "coolant overflow", "fan clearance"],
  electronics: ["kill switch", "quick shifter", "battery cable", "dash mount", "sensor connector"],
  drivetrain: ["chain", "master link", "shift rod", "sprocket", "clutch lever", "rearset"],
  unknown: ["controls", "brakes", "wheels", "suspension", "cooling", "fluid leaks", "bodywork clearance"],
};

// Sample paddock-location lookup for cards: { userId -> Pn }
export const paddockOf = (userId: string) =>
  demoCheckIns.find((ci) => ci.userId === userId)?.paddockLocation;
